#!/bin/bash

set -e

SDCARD=/dev/mmcblk0
DOCKER_IMAGE=df-orangepi-zero

docker buildx build --progress=plain . --load -t $DOCKER_IMAGE

docker run --rm -it --device=$SDCARD:/build/sdcard:rwm --cap-add SYS_ADMIN $DOCKER_IMAGE /build/step1
docker run --rm -it --device=${SDCARD}p1:/build/part-root:rwm --device=${SDCARD}p2:/build/part-data:rwm --cap-add SYS_ADMIN --security-opt apparmor=unconfined $DOCKER_IMAGE /build/step2

