#!/bin/bash
set -e

DEVICE=/dev/mmcblk0
DOCKER_IMAGE=defa/rpi-2-b

docker run \
    --rm \
    -it \
    -e ROOT_SIZE_MB=100 \
    --device=$DEVICE:/build/device:rwm \
    --cap-add SYS_ADMIN \
    $DOCKER_IMAGE \
    /build/install-step1

docker run \
    --rm \
    -it \
    -v $(pwd)/custom-root:/build/custom-root \
    --device=${DEVICE}p1:/build/p1:rwm \
    --device=${DEVICE}p2:/build/p2:rwm \
    --cap-add SYS_ADMIN \
    --security-opt apparmor=unconfined \
    $DOCKER_IMAGE \
    /build/install-step2

sync
echo "> Done."