#!/bin/bash

set -x

sudo umount /dev/mmcblk0p1
set -e

sudo mount /dev/mmcblk0p1 /mnt
#sudo docker cp ib:/build/linux/arch/arm64/boot/Image /mnt
sudo docker cp ib:/build/linux/arch/arm/boot/zImage /mnt
sudo umount /dev/mmcblk0p1