#!/bin/bash

# https://linux-sunxi.org/Bootable_SD_card#Bootloader

set -e

echo "[step] Installing U-BOOT..."
dd if=u-boot/u-boot-sunxi-with-spl.bin of=sdcard bs=1024 seek=8

echo "[step] Creating partition table..."

sfdisk sdcard <<EOT
1M,300M,L
,500M,L
EOT

