#!/bin/bash

# https://linux-sunxi.org/Bootable_SD_card#Bootloader

set -e

echo "[step] Creating file systems..."
mkfs.ext4 -F -L ROOT part-root
#mkfs.ext4 -F -L DATA part-data

mount part-root mount-root

mkdir mount-root/boot
cp boot.scr mount-root/boot
cp linux/arch/arm/boot/dts/sun8i-h2-plus-orangepi-zero.dtb mount-root/boot
cp linux/arch/arm/boot/zImage mount-root/boot

cp -r alpine/* mount-root
#cp -r copy-root/* mount-root

#bash

umount mount-root

sync
echo "[step] Done."
