#!/bin/sh

# https://linux-sunxi.org/Bootable_SD_card#Bootloader

set -e

echo "> Installing U-BOOT..."
dd if=u-boot-sunxi-with-spl.bin of=sdcard bs=1024 seek=8

echo "> Creating partition table..."

sfdisk sdcard <<EOT
1M,300M,L
,500M,L
EOT

