WORKDIR ..

RUN git clone -c advice.detachedHead=false --depth 1 -b master-2023-09-01 git://git.kernel.org/pub/scm/linux/kernel/git/sforshee/wireless-regdb.git
RUN mv wireless-regdb/regulatory.db /build/firmware
RUN mv wireless-regdb/regulatory.db.p7s /build/firmware
RUN rm -rf wireless-regdb

WORKDIR linux

