#!/bin/sh
set -e

echo "> Creating file systems..."
mkfs.ext4 -F -L ROOT part-root
mkfs.ext4 -F -L DATA part-data

echo "> Copying root file system..."

mkdir mount-root
mount part-root mount-root
cp -r copy-root/* mount-root
echo "nameserver 8.8.8.8" >mount-root/etc/resolv.conf
cp -r customize-root/* mount-root
umount mount-root

sync
echo "> Done."
