#!/bin/sh

apk add \
    alpine-base \
    dhcp \
    wireguard-tools \
    docker \
    iptables \
    ip6tables \
    wpa_supplicant \
    dropbear \
    mc \
    tree

rc-update add devfs sysinit
rc-update add mdev sysinit
rc-update add bootmisc boot
rc-update add hostname boot
rc-update add hwclock boot
rc-update add loopback boot
rc-update add networking boot
rc-update add cgroups boot
rc-update add syslog boot
rc-update add mount-ro shutdown
rc-update add killprocs shutdown
rc-update add savecache shutdown
rc-update add dropbear default
rc-update add ntpd default
rc-update add docker default
