FROM ubuntu:23.10 AS cc-stage

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y \
    git \
    build-essential \
    libncurses-dev \
    bison \
    flex \
    swig \
    python3-pip \
    python3-distutils \
    bc \
    util-linux \
    dosfstools \
    libssl-dev \
    libelf-dev \
    curl
