FROM alpine:latest AS installer-stage

RUN apk add sfdisk e2fsprogs

WORKDIR /build

ARG LINUX_DT_NAME
ARG GCC_ARCH

COPY --from=root-stage / copy-root/
COPY root copy-root/
COPY --from=kernel-stage /build/linux/arch/${GCC_ARCH}/boot/bzImage copy-root/boot/bzImage
#COPY --from=kernel-stage /build/linux/arch/${GCC_ARCH}/boot/dts/${LINUX_DT_NAME}.dtb copy-root/boot/dt.dtb
COPY --from=uboot-stage /build/boot.scr copy-root/boot/boot.scr
COPY --from=uboot-stage /build/u-boot/*.bin u-boot/
COPY --from=uboot-stage /build/u-boot/*.dtb u-boot/
COPY --from=uboot-stage /build/u-boot/*.rom u-boot/

COPY install-* ./
