#!/bin/sh
set -e

DEVICE=/host-dev/mmcblk0
ROOT_SIZE_MB=${ROOT_SIZE_MB:-500}

echo "> Creating partition table, root size is ${ROOT_SIZE_MB}M..."

sfdisk --wipe always $DEVICE <<EOT
1M,${ROOT_SIZE_MB}M,L
,100M,L
EOT

