#!/bin/sh
set -e

echo "> Creating file systems..."
mkfs.ext4 -F -L ROOT /build/p1
mkfs.ext4 -F -L DATA /build/p2

echo "> Mounting file systems..."
mkdir /build/mount
mount /build/p1 /build/mount
mkdir /build/mount/data
mount /build/p2 /build/mount/data

./install-mount /build/mount

umount mount/data
umount mount

