FROM cc-stage AS kernel-stage

ENV CROSS_COMPILE=${GCC_CROSS_COMPILE}

WORKDIR /build
RUN git clone -c advice.detachedHead=false --depth 1 -b ${LINUX_VERSION} ${LINUX_REPO}

COPY linux linux

WORKDIR /build/linux

COPY linux.patch .
RUN cat linux.patch | patch -p1

ENV LINUX_ARCH=${LINUX_ARCH}
ENV ARCH=${LINUX_ARCH}

COPY linux-defconfig .
RUN cat linux-defconfig >>arch/${LINUX_ARCH}/configs/${LINUX_DEFCONFIG}; rm linux-defconfig

COPY firmware /build/firmware
RUN rm /build/firmware/.keepme
RUN echo "CONFIG_EXTRA_FIRMWARE=\"$(find /build/firmware -type f -printf '%P ')\"" >>arch/${LINUX_ARCH}/configs/${LINUX_DEFCONFIG}

