FROM ubuntu:21.04 AS cc-stage

ARG GCC_ARCH
ARG GCC_CROSS_COMPILE

ENV ARCH=${GCC_ARCH}
ENV CROSS_COMPILE=${GCC_CROSS_COMPILE}

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
RUN apt-get install -y \
    git \
    build-essential \
    libncurses-dev \
    bison \
    flex \
    swig \
    python3-pip \
    python3-distutils \
    bc \
    util-linux \
    dosfstools \
    libssl-dev \
    libelf-dev \
    curl
    