FROM cc-stage AS uboot-stage

WORKDIR /build

RUN git clone -c advice.detachedHead=false --depth 1 -b ${UBOOT_VERSION} ${UBOOT_REPO}

WORKDIR /build/u-boot

RUN make ${UBOOT_DEFCONFIG}
RUN make

WORKDIR /build

COPY boot.cmd ./
RUN mkimage -C none -A ${ARCH} -T script -d boot.cmd boot.scr

