FROM alpine:latest AS installer-stage

RUN apk add sfdisk e2fsprogs dtc

WORKDIR /build

COPY --from=root-stage / root/
COPY root root/

RUN mkdir custom-root

COPY install ./
COPY install-* ./

ARG LINUX_ARCH

CMD ./install

