#!/bin/sh
set -e

PART_PREFIX=/build/p

echo "> Creating file systems..."
. ./install-mkfs

echo "> Mounting file systems..."
MOUNT=/build/mount
mkdir $MOUNT
mount ${PART_PREFIX}2 $MOUNT
mkdir $MOUNT/boot
mount ${PART_PREFIX}1 $MOUNT/boot
mkdir $MOUNT/data
mount ${PART_PREFIX}3 $MOUNT/data

. ./install-mount

umount $MOUNT/boot
umount $MOUNT/data
umount $MOUNT

