#!/bin/bash
set -e

function build() {
    $(dirname $0)/build $@
}

#build defa/rpi-2-b rpi-2-b dropbear avahi
build defa/orangepi-zero orangepi-zero dropbear avahi ./device-farm
#build defa/nanopi-duo nanopi-duo dropbear avahi

#build defa/qemu_x86_64 qemu_x86_64 dropbear avahi
