#!/bin/bash
set -e

cd $1

addVar() {
    KEY=$1
    VALUE=$2
    echo "$KEY=\"$VALUE\""
    eval "$KEY=\"$VALUE\""
    DOCKER_BUILD_ARGS="$DOCKER_BUILD_ARGS --build-arg \"$KEY=$VALUE\""
}

addVar BOARD_ID $(basename $1)

DIRS=$1
while true; do
    INV_DIRS="$DIRS $INV_DIRS"
    if [ $(basename $DIRS) = boards ]; then
        break
    fi
    DIRS=$(dirname $DIRS)
done

echo "Building installer image for $BOARD_NAME ($BOARD_ID)"

DOCKER_IMAGE=defa/install-$BOARD_ID
DOCKER_CTX=/tmp/ctx-$BOARD_ID
rm -rf $DOCKER_CTX
mkdir -p $DOCKER_CTX/root/etc/defa

for DIR in $INV_DIRS; do

    for FILE in $(find $DIR -maxdepth 1 -type f)
    do
        if [[ $FILE =~ .*\.append$ ]]
        then
            DST=$DOCKER_CTX/$(basename $(sed s/.append$// <<<$FILE))
            cat $FILE >>$DST
        else
            cp $FILE $DOCKER_CTX
        fi
    done

    if [ -d $DIR/[root] ]
    then
        cp -r $DIR/[root]/. $DOCKER_CTX/root
    fi
done

tree $DOCKER_CTX

for FILE in $DOCKER_CTX/_*
do    
    KEY=$(echo $(basename $FILE) | sed s/^.//)
    VALUE=$(cat $DOCKER_CTX/_$KEY)
    addVar "$KEY" "$VALUE"
done

echo sh -c "docker buildx build --progress=plain --load $DOCKER_BUILD_ARGS $DOCKER_CTX -t $DOCKER_IMAGE"

echo "Published as $DOCKER_IMAGE"


