#!/bin/bash
set -e

LINUX_DIR=$1

if [ -z $LINUX_DIR ]
then
    echo "Use: $(basename $0) <linux-source-dir>"
    exit 1
fi

BUILDER_DIR=$(readlink --canonicalize $(dirname $0))

echo "LINUX_DIR=$LINUX_DIR"
echo "BUILDER_DIR=$BUILDER_DIR"

export ARCH=arm
export CROSS_COMPILE=arm-none-eabi-
export DEFCONFIG=multi_v7_defconfig

cd $LINUX_DIR

make defconfig
make savedefconfig
cp defconfig defconfig-clean

cat arch/$ARCH/configs/$DEFCONFIG >arch/$ARCH/configs/tmp_defconfig
cat $BUILDER_DIR/boards/ext-defconfig-linux >>arch/$ARCH/configs/tmp_defconfig
make tmp_defconfig
make menuconfig
make savedefconfig
diff defconfig defconfig-clean | grep "^< " | sed "s/^< //" | sort >$BUILDER_DIR/boards/ext-defconfig-linux

echo "Done. The config fragment is:"
echo "------------------------------------------------------"
cat $BUILDER_DIR/boards/ext-defconfig-linux
echo "------------------------------------------------------"
