#!/bin/bash
set -e

DEFCONFIG_PATH=$1
LINUX_DIR=$2

if [ -z "$DEFCONFIG_PATH" -o -z "$LINUX_DIR" ]
then
    echo "Use: $(basename $0) <defconfig-fragment-path> <linux-source-dir>"
    exit 1
fi

DEFCONFIG_PATH=$(readlink --canonicalize $DEFCONFIG_PATH)

echo "DEFCONFIG_PATH=$DEFCONFIG_PATH"
echo "LINUX_DIR=$LINUX_DIR"

#export ARCH=arm
#export LINUX_ARCH=arm
#export CROSS_COMPILE=arm-none-eabi-
#export DEFCONFIG=multi_v7_defconfig

export ARCH=arm64
export LINUX_ARCH=arm64
export CROSS_COMPILE=arm-none-eabi-
export DEFCONFIG=allnoconfig

#export LINUX_ARCH=x86
#export DEFCONFIG=x86_64_defconfig

cd $LINUX_DIR

make defconfig
make savedefconfig
cp defconfig defconfig-clean

cat arch/$LINUX_ARCH/configs/$DEFCONFIG >arch/$LINUX_ARCH/configs/tmp_defconfig
cat $DEFCONFIG_PATH >>arch/$LINUX_ARCH/configs/tmp_defconfig
make tmp_defconfig
make menuconfig
make savedefconfig
diff defconfig defconfig-clean | grep "^< " | sed "s/^< //" | sort >$DEFCONFIG_PATH

echo "Done. The config fragment is:"
echo "------------------------------------------------------"
cat $DEFCONFIG_PATH
echo "------------------------------------------------------"
