RUN apk add xorg-server xinit

COPY <<EOF /etc/init.d/xorg-server
#!/sbin/openrc-run

function depend()
{
    need net
}

function start()
{
    xinit /etc/xinitrc &
}

function stop()
{
    pkill xinit || true
}
EOF

RUN chmod 777 /etc/init.d/xorg-server

RUN rc-update add xorg-server
