#!/bin/bash

set -e 

rm -rf /tmp/wireguard-linux-compat
git clone -c advice.detachedHead=false --depth 1 -b v1.0.20210424 https://github.com/WireGuard/wireguard-linux-compat.git /tmp/wireguard-linux-compat

/tmp/wireguard-linux-compat/kernel-tree-scripts/create-patch.sh >linux.patch.append

